# Site settings
title: Zoomina
email: clover_328@naver.com
url: https://zoomina.github.io
description: "자민 포트폴리오"
keywords: "your keywords"
skills: "Data Analyst"
meta_author: Jamin Byeon

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/zoomina?utm_source=website&utm_campaign=contact_me&utm_content=footer&utm_medium=githubpage
  - title: github
    url: http://github.com/zoomina

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

# Multi-language settings
languages: ["en", "ko"]
default_lang: "en"
exclude_from_localizations: ["js", "css", "img"]

plugins:
  - jekyll-multiple-languages-plugin

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
